site_name: Onibolt Docs Site
site_url: https://docs.onibolt.com
copyright: Copyright &copy; 2022

# Repository information
repo_name: onibolt/docs-site
repo_url: https://github.com/onibolt/docs-site
edit_uri: edit/main/docs/docs/

nav:
  - Home: README.md
  - Docs: docs.md
extra_css:
    - css/custom.css
theme:
  name: material
  font:
    text: Montserrat
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'indigo'
      accent: 'deep orange'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'deep orange'
      accent: 'indigo'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc:
      title: Table of Contents
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
    - search